# Generated by Django 4.0.3 on 2022-06-07 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=500)),
                ('rating', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')])),
                ('date', models.DateField(auto_now_add=True)),
                ('usefulCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('se', models.CharField(max_length=50)),
                ('freq', models.DecimalField(decimal_places=2, max_digits=5)),
                ('incr', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('numTel', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male '), ('Female', 'Female ')], default='male ', max_length=10)),
                ('med_history', models.TextField(blank=True, max_length=800)),
                ('Wilaya', models.CharField(blank=True, max_length=30)),
                ('poids', models.IntegerField()),
                ('taille', models.IntegerField()),
                ('preg', models.BooleanField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
